-- 007_principals_members: principals and members become RECORDS (S1.1a).
--
-- Additive only. Two new tables, nothing dropped, no existing row touched.
--
-- Until now a member was a line in adapters.yaml and a principal was a string inside it.
-- That was right while the roster was configuration. Four things were waiting on records:
-- mandates key to member ids nothing validated, the web tier read the roster off the
-- filesystem (UI2-N2), principal display names were invented in config, and every identity
-- finding from M-N1 onward needs something to authenticate AGAINST.
--
-- THIS MIGRATION CREATES STRUCTURE. IT AUTHENTICATES NOTHING. S1.2 does that, and the
-- distinction is load-bearing: a `members` table makes enrolment expressible and the binding
-- structural, and it still cannot tell you that the caller claiming to be `prince` is Prince.
-- See RA-006 for the exit-criterion amendment that says so.

CREATE TABLE IF NOT EXISTS principals (
  id           TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  -- ACCENT ORDER AS A STORED FACT, not a position in a config array.
  --
  -- S-UI2 assigned a principal's colour from its index in adapters.yaml, which made the
  -- colour a property of file order. Ordering here by `created_at` would have been worse:
  -- the seed writes both rows in one statement with one timestamp, so it would fall through
  -- to the id and hand Prince accent 1 and Jerry accent 0 — recolouring the room on a
  -- migration. The number is explicit because it is the thing that must not move.
  ordinal      INTEGER NOT NULL UNIQUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS members (
  id           TEXT PRIMARY KEY,
  -- 'human' or 'agent'. A CHECK rather than an enum type: adding a kind later is then an
  -- additive migration rather than an ALTER TYPE that locks the table.
  kind         TEXT NOT NULL CHECK (kind IN ('human', 'agent')),
  display_name TEXT NOT NULL,
  -- THE BINDING, AND THE POINT OF THE SLICE. NOT NULL plus a foreign key: a member cannot
  -- exist without a principal, and the principal it names must exist. Enforced here rather
  -- than in application code for the same reason migrations 005 and 006 enforced the summon
  -- invariants at the database — a check in a command survives neither a second instance nor
  -- a hand-run INSERT, and this is the binding every later authority claim rests on.
  principal_id TEXT NOT NULL REFERENCES principals (id),
  -- An AGENT member references an adapter; a HUMAN member does not. No foreign key: adapters
  -- live in adapters.yaml, not in this database, and §6 keeps them there. The reference is
  -- validated at load against the registry instead, and that is stated rather than implied.
  adapter_id   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT members_agent_has_adapter CHECK (
    (kind = 'agent' AND adapter_id IS NOT NULL) OR
    (kind = 'human' AND adapter_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS members_principal_idx ON members (principal_id);

-- ── SEED ─────────────────────────────────────────────────────────────────────────────
--
-- THE MIGRATION PATH, NOT A FIXTURE. These rows are the roster adapters.yaml held at
-- S11a-1, transcribed field for field, so this commit changes nothing a viewer can see.
--
-- Written as SQL rather than generated by a script at deploy time for one reason: the next
-- commit removes `display_name` and `principal` from adapters.yaml, so a script that derives
-- the seed from that file would stop working the moment it became the only way to populate a
-- fresh database — including CI's. A migration is the right home for a historical fact.
--
-- Its faithfulness is not asserted by a comment. `members.seed.test.ts` compares these rows
-- against adapters.yaml field by field while that file still carries them, which is the only
-- window in which the equivalence is checkable at all.
--
-- Ordinals are adapters.yaml's declared principal order: prince 0, jerry 1. Those are the
-- accents the room shows today and they must not move.
INSERT INTO principals (id, display_name, ordinal) VALUES
  ('principal:prince', 'Prince', 0),
  ('principal:jerry',  'Jerry',  1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO members (id, kind, display_name, principal_id, adapter_id) VALUES
  ('claude-main', 'agent', 'Claude', 'principal:prince', 'claude-main'),
  ('sol',         'agent', 'Sol',    'principal:jerry',  'sol')
ON CONFLICT (id) DO NOTHING;
